version: '3.9'

services:
  mongo:
    image: 'mongo'
    container_name: 'mongodb'
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
  node:
    build: ./node
    env_file:
      - '.env'
    environment:
      - API_PORT=${API_PORT}
      - DB_URL=${DB_URL}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - SECRET_KEY=${SECRET_KEY}
    restart: always
    volumes:
      - ./node:/srv/node
      - ./config:/srv/config
    ports:
      - '${API_PORT}:${API_PORT}'
    depends_on:
      - mongo
  python:
    build: ./python
    env_file:
      - '.env'
    environment:
      - NODE_PORT=${API_PORT}
      - SECRET_KEY=${SECRET_KEY}
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ./python:/srv/python
      - ./config:/srv/config
    depends_on:
      - node
